"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobalStyle = void 0;
var styled_components_1 = require("styled-components");
exports.GlobalStyle = (0, styled_components_1.createGlobalStyle)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\n* {\n  body {\n    margin: 0;\n    font-family: 'Roboto';\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n  }\n\n    button {\n      text-transform: none !important\n    }\n\n\n  .title {\n    font-size: 36.63px;\n    font-weight: 500;\n  }\n\n  .subtitle {\n    font-size: 29.3px;\n    font-weight: 500;\n  }\n\n  .texto5 {\n    font-size: 23.44px;\n    font-weight: 500;\n  }\n\n  .texto4 {\n    font-size: 18.75px;\n    font-weight: 500;\n  }\n\n  .texto3 {\n    font-size: 15px;\n    font-weight: 500;\n  }\n\n  .texto2 {\n    font-size: 12px;\n    font-weight: 500;\n  }\n\n  .texto1 {\n    font-size: 10px;\n    font-weight: 500;\n  }\n\n  .titleExtraBold {\n    font-size: 36.63px;\n    font-weight: 800;\n  }\n\n  .subtitleExtraBold {\n    font-size: 29.3px;\n    font-weight: 800;\n  }\n\n  .texto5ExtraBold{\n    font-size: 23.44px;\n    font-weight: 800;\n  }\n\n  .texto4ExtraBold {\n    font-size: 18.75px;\n    font-weight: 800;\n  }\n}\n"], ["\n\n* {\n  body {\n    margin: 0;\n    font-family: 'Roboto';\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n  }\n\n    button {\n      text-transform: none !important\n    }\n\n\n  .title {\n    font-size: 36.63px;\n    font-weight: 500;\n  }\n\n  .subtitle {\n    font-size: 29.3px;\n    font-weight: 500;\n  }\n\n  .texto5 {\n    font-size: 23.44px;\n    font-weight: 500;\n  }\n\n  .texto4 {\n    font-size: 18.75px;\n    font-weight: 500;\n  }\n\n  .texto3 {\n    font-size: 15px;\n    font-weight: 500;\n  }\n\n  .texto2 {\n    font-size: 12px;\n    font-weight: 500;\n  }\n\n  .texto1 {\n    font-size: 10px;\n    font-weight: 500;\n  }\n\n  .titleExtraBold {\n    font-size: 36.63px;\n    font-weight: 800;\n  }\n\n  .subtitleExtraBold {\n    font-size: 29.3px;\n    font-weight: 800;\n  }\n\n  .texto5ExtraBold{\n    font-size: 23.44px;\n    font-weight: 800;\n  }\n\n  .texto4ExtraBold {\n    font-size: 18.75px;\n    font-weight: 800;\n  }\n}\n"])));
var templateObject_1;
